sudo: false

git:
  depth: 5

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install:
  - npm install -g npm@latest

matrix:
  include:
    - node_js: '10'
      script: npm run jest -- --maxWorkers=2 --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      env: CI=coverage
    - node_js: '8'
      script: npm run jest -- --maxWorkers=2
      env: CI=tests 8
    - node_js: '12'
      script: npm run jest -- --maxWorkers=2
      env: CI=tests 12
